<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SZDJZBDT0105" ignored="3" name="testng(failed)" tests="2" failures="2" timestamp="18 一月 2019 06:38:05 GMT" time="0.002" errors="0">
  <testcase name="test03" time="0.0" classname="demo1.ReRunFailedTestCaseDemo">
    <failure type="java.lang.AssertionError" message="expected [13] but found [11]">
      <![CDATA[java.lang.AssertionError: expected [13] but found [11]
at demo1.ReRunFailedTestCaseDemo.test03(ReRunFailedTestCaseDemo.java:18)
at demo1.RunTestNG.main(RunTestNG.java:21)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test03 -->
  <testcase name="test05" time="0.0" classname="demo1.ReRunFailedTestCaseDemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo1.ReRunFailedTestCaseDemo.test05(ReRunFailedTestCaseDemo.java:27)
at demo1.RunTestNG.main(RunTestNG.java:21)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test05 -->
  <testcase name="test01" time="0.0" classname="demo1.ReRunFailedTestCaseDemo">
    <ignored/>
  </testcase> <!-- test01 -->
  <testcase name="test04" time="0.0" classname="demo1.ReRunFailedTestCaseDemo">
    <ignored/>
  </testcase> <!-- test04 -->
  <testcase name="test02" time="0.0" classname="demo1.ReRunFailedTestCaseDemo">
    <ignored/>
  </testcase> <!-- test02 -->
</testsuite> <!-- testng(failed) -->
